var verse = [
  `For by grace you have been saved through faith; and this is not your own doing, it is the gift of God\n\n<i><small>EPHESIANS 2:8</small></i>`,
  `Cast all your anxiety on Him, for He cares about you\n\n<i><small>1 PETER 5:7</small></i>`,
  `I believe that I shall see the goodness of the Lord in the land of the living!\n\n<i><small>PSALM 27:13</small></i>`,
  `Hitherto you have asked nothing in my name; ask, and you will receive, that your joy may be full\n\n<i><small>JOHN 16:24</small></i>`,
  `The least one shall become a clan, and the smallest one a mighty nation; I am the Lord; in its time I will hasten it\n\n<i><small>ISAIAH 60:22</small></i>`,
  `And I will make them and the places round about my hill a blessing; and I will send down the showers in their season; they shall be showers of blessing\n\n<i><small>EZEKIEL 34:26</small></i>`,
  `Remember not the former things, nor consider the things of old\n\n<i><small>ISAIAH 43:18</small></i>`,
  `Let no evil talk come out of your mouths, but only such as is good for edifying, as fits the occasion, that it may impart grace to those who hear\n\n<i><small>EPHESIANS 4:29</small></i>`,
  `The way of a fool is right in his own eyes, but a wise man listens to advice\n\n<i><small>PROVERBS 12:15</small></i>`,
  `Give to everyone who begs from you; and if anyone takes away your goods, do not ask for them again\n\n<i><small>LUKE 6:30</small></i>`,
  `And as you wish that men would do to you, do so to them\n\n<i><small>LUKE 6:31</small></i>`,
  `For God did not give us a spirit of timidity but a spirit of power and love and self-control\n\n<i><small>2 TIMOTHY 1:7</small></i>`,
  `God is our refuge and strength, a very present help in trouble\n\n<i><small>PSALM 46:1</small></i>`,
  `So Christ, having been offered once to bear the sins of many, will appear a second time, not to deal with sin but to save those who are eagerly waiting for Him\n\n<i><small>HEBREWS 9:28</small></i>`,
  `But you, take courage! Do not let your hands be weak, for your work shall be rewarded\n\n<i><small>2 CHRONICLES 15:7</small></i>`,
  `For God is not unjust so as to overlook your work and the love which you showed for His sake in serving the saints, as you still do\n\n<i><small>HEBREWS 6:10</small></i>`,
  `Come to me, all who labor and are heavy laden, and I will give you rest\n\n<i><small>MATTHEW 11:28</small></i>`,
  `Do nothing from selfishness or conceit, but in humility count others better than yourselves\n\n<i><small>PHILIPPIANS 2:3</small></i>`,
  `For the word of God is living and active, sharper than any two-edged sword, piercing to the division of soul and spirit, of joints and marrow, and discerning the thoughts and intentions of the heart\n\n<i><small>HEBREWS 4:12</small></i>`,
  `A friend loves at all times, and a brother is born for adversity\n\n<i><small>PROVERBS 17:17</small></i>`,
  `My son, do not forget my teaching, but let your heart keep my commandments; for length of days and years of life and abundant welfare will they give you\n\n<i><small>PROVERBS 3:1</small></i>`,
  `Then you will walk on your way securely and your foot will not stumble. If you sit down, you will not be afraid; when you lie down, your sleep will be sweet\n\n<i><small>PROVERBS 3:23-24</small></i>`,
  `It is the Lord who goes before you; He will be with you, He will not fail you or forsake you; do not fear or be dismayed\n\n<i><small>DEUTERONOMY 31:8</small></i>`,
  `Blessed be the God and Father of our Lord Jesus Christ, the Father of mercies and God of all comfort, who comfort us in all our affliction, so that we may be able to comfort with which we ourselves are comforted by God\n\n<i><small>2 CORINTHIANS 1:3-4</small></i>`,
  `A man's mind plans his way, but the Lord directs his steps\n\n<i><small>PROVERBS 16:9</small></i>`,
  `And the Lord will become King over all the earth; on that day the Lord will be one and His name one\n\n<i><small>ZECHARIAH 14:9</small></i>`,
  `But Jesus looked at them and said to them, "With men this is impossible, but with God all things are possible"\n\n<i><small>MATTHEW 19:26</small></i>`,
  `Better is a little with the fear of the Lord than great treasure and trouble with it\n\n<i><small>PROVERBS 15:16</small></i>`,
  `For thou dost bless the righteous, O Lord; thou dost cover him with favor as with a shield\n\n<i><small>PSALM 5:12</small></i>`,
  `Who is wise and understanding among you? By his good life let him show his works in the meekness of wisdom\n\n<i><small>JAMES 3:13</small></i>`,
  `But if you have bitter jealousy and selfish ambition in your hearts, do not boast and be false to the truth\n\n<i><small>JAMES 3:14</small></i>`,
  `For where jealousy and selfish ambition exist, there will be disorder and every vile practice\n\n<i><small>JAMES 3:16</small></i>`,
  `A righteous man who walks in his integrity-blessed are his sons after him!\n\n<i><small>PROVERBS 20:7</small></i>`,
  `Love not sleep, lest you come to poverty; open your eyes, and you will have plenty of bread\n\n<i><small>PROVERBS 20:13</small></i>`,
  `If the Spirit of Him who raised Jesus from the dead dwells in you, He who raised Christ Jesus from the dead will give life to your mortal bodies also through His Spirit who dwells in you\n\n<i><small>ROMANS 8:11</small></i>`,
  `Yet if one suffers as a Christian, let him not be ashamed, but under that name let him glorify God\n\n<i><small>1 PETER 4:16</small></i>`,
  `But when you pray, go into your room and shut the door and pray to your Father who is in secret; and your Father who sees in secret will reward you\n\n<i><small>MATTHEW 6:6</small></i>`,
  `For  if you forgive men their trespasses, your heavenly Father also will forgive you; but if you do not forgive men their trespasses, neither will your Father forgive your trespasses\n\n<i><small>MATTHEW 6:14-15</small></i>`,
  `Keep your heart with all vigilance; for from it flow the springs of life\n\n<i><small>PROVERBS 4:23</small></i>`,
  `But the path of the righteous is like the light of dawn, which shines brighter and brighter until full day\n\n<i><small>PROVERBS 4:18</small></i>`,
  `So teach us to number our days that we may get a heart of wisdom\n\n<i><small>PSALM 90:12</small></i>`,
  `Blessed is the man who trusts in the Lord, whose trust is the Lord\n\n<i><small>JEREMIAH 17:7</small></i>`,
  `The heart is deceitful above all things, and desperately corrupt; who can understand it?\n\n<i><small>JEREMIAH 17:9</small></i>`,
  `Trust in the Lord forever, for the Lord God is an everlasting rock\n\n<i><small>ISAIAH 26:4</small></i>`,
  `Blessed are those whose way is blameless, who walk in the law of the Lord! Blessed are those who keep His testimonies, who seek Him with their whole heart\n\n<i><small>PSALM 119:1-2</small></i>`,
  `What you have learned and received and heard and seen in me, do; and the God of peace will be with you\n\n<i><small>PHILIPPIANS 4:9</small></i>`,
  `I can do all things in Him who strengthens me\n\n<i><small>PHILIPPIANS 4:13</small></i>`,
  `So you, by the help of your God, return, hold fast to love and justice, and wait continually for your God\n\n<i><small>HOSEA 12:6</small></i>`,
  `I wait for the Lord, my soul waits, and in His word I hope\n\n<i><small>PSALM 130:5</small></i>`,
  `For you were called to freedom, brethren; only do not use your freedom as an opportunity for the flesh, but through love be servants of one another\n\n<i><small>GALATIANS 5:13</small></i>`,
  `And every tongue confess that Jesus Christ is Lord, to the glory of God the Father\n\n<i><small>PHILIPPIANS 2:11</small></i>`,
  `Set your minds on things that are above, not on things that are on earth\n\n<i><small>COLOSSIANS 3:2</small></i>`,
  `For you have died, and your life is hid with Christ in God\n\n<i><small>COLOSSIANS 3:3</small></i>`,
  `Blessed is everyone who fears the Lord, who walks in His ways!\n\n<i><small>PSALM 128:1</small></i>`,
  `Trust in the Lord with all your heart, and do not rely on your own insight. In all your ways acknowledge Him, and He will make straight your paths\n\n<i><small>PROVERBS 3:5-6</small></i>`,
  `And you shall love the Lord your God with all your heart, and with all your soul, and with all your mind, and with all your strength\n\n<i><small>MARK 12:30</small></i>`,
  `When the cares of my heart are many, Thy consolations cheer my soul\n\n<i><small>PSALM 94:19</small></i>`,
  `But I say to you that hear, Love your enemies, do good to those who hate you, bless those who curse you, pray for those who abuse you\n\n<i><small>LUKE 6:27-28</small></i>`,
  `So faith, hope, love, abide these three; but the greatest of these is love\n\n<i><small>1 CORINTHIANS 13:13</small></i>`,
  `And though your beginning was small, your latter days will be very great\n\n<i><small>JOB 8:7</small></i>`,
  `I know the Lord is always with me\n\n<i><small>PSALM 16:8</small></i>`,
  `Finally, brethren, whatever is true, whatever is honorable, whatever is just, whatever is pure, whatever is lovely, whatever is gracious, if there is any excellence, if there is anything worthy of praise, think about these things\n\n<i><small>PHILIPPIANS 4:8</small></i>`,
  `Make me to know thy ways, O Lord; teach me thy paths. Lead me in thy truth, and teach me, for thou art the God of my salvation; for thee I wait all the day long\n\n<i><small>PSALM 25:4-5</small></i>`,
  `Enter His gates with thanksgiving, and His courts with praise! Give thanks to Him, bless His name!\n\n<i><small>PSALM 100:4</small></i>`,
  `He is not here; for He has risen, as He said. Come, see the place where He lay\n\n<i><small>MATTHEW 28:6</small></i>`,
  `In all your ways acknowledge Him, and He will make straight your paths\n\n<i><small>PROVERBS 3:6</small></i>`,
  `Happy is the man who finds wisdom, and the man who gets understanding, for the gain from it is better than gain from silver and its profit better than gold\n\n<i><small>PROVERBS 3:13-14</small></i>`,
  `She is more precious than jewels, and nothing you desire can compare with her\n\n<i><small>PROVERBS 3:15</small></i>`,
  `One man gives freely, yet grows all the richer; another withholds what he should give, and only suffers want\n\n<i><small>PROVERBS 11:24</small></i>`,
  `The Lord lift up His countenance upon you, and give you peace\n\n<i><small>NUMBERS 6:26</small></i>`,
  `With all lowliness and meekness, with patience, forbearing one another in love, eager to maintain the unity of the Spirit in the bond of peace\n\n<i><small>EPHESIANS 4:2-3</small></i>`,
  `Even a fool who keeps silent is considered wise; when he closes his lips, he is deemed intelligent\n\n<i><small>PROVERBS 17:28</small></i>`,
  `O come, let us worship and bow down, let us kneel before the Lord, our Maker!\n\n<i><small>PSALM 95:6</small></i>`,
  `But I say, walk by the Spirit, and do not gratify the desires of the flesh\n\n<i><small>GALATIANS 5:16</small></i>`,
  `But they who wait for the Lord shall renew their strength, they shall mount up with wings like eagles, they shall run and not be weary, they shall walk and not faint\n\n<i><small>ISAIAH 40:31</small></i>`,
  `For where your treasure is, there your heart will also be\n\n<i><small>MATTHEW 6:21</small></i>`,
  `Rejoice in your hope, be patient in tribulation, be constant in prayer\n\n<i><small>ROMANS 12:12</small></i>`,
  `For the Lord is good; His steadfast love endures forever, and His faithfulness to all generations\n\n<i><small>PSALM 100:5</small></i>`,
  `And let the peace of Christ rule in your hearts, to which indeed you were called in the one body\n\n<i><small>COLOSSIANS 3:15</small></i>`,
  `And it is my prayer that your love may abound more and more, with knowledge and all discernment\n\n<i><small>PHILIPPIANS 1:9</small></i>`,
  `Some boast of chariots, and some of horses; but we boast in the name of the Lord our God\n\n<i><small>PSALM 20:7</small></i>`,
  `My flesh and my heart may fail, but God is the strength of my heart and my portion forever\n\n<i><small>PSALM 73:26</small></i>`,
  `He who is greatest among you shall be your servant\n\n<i><small>MATTHEW 23:11</small></i>`,
  `Thy word is a lamp to my feet and a light to my path\n\n<i><small>PSALM 119:105</small></i>`,
  `Thus says the Lord: "Keep your voice from weeping, and your eyes from tears; for your work shall be rewarded", says the Lord and they shall come back from the land of the enemy\n\n<i><small>JEREMIAH 31:16</small></i>`,
  `"There is hope for your future", says the Lord, and your children shall come back to their own country\n\n<i><small>JEREMIAH 31:17</small></i>`,
  `The true light that enlightens every man was coming into the world\n\n<i><small>JOHN 1:9</small></i>`,
  `We know that in everything God works for good with those who love Him, who are called according to His purpose\n\n<i><small>ROMANS 8:28</small></i>`,
  `But seek first His kingdom and His righteousness, and all these things shall be yours as well\n\n<i><small>MATTHEW 6:33</small></i>`,
  `The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid?\n\n<i><small>PSALM 27:1</small></i>`,
  `O give thanks to the Lord, for He is good; His steadfast love endures forever!\n\n<i><small>PSALM 118:1</small></i>`,
  `In God I trust without a fear. What can man do to me?\n\n<i><small>PSALM 56:11</small></i>`,
  `Looking to Jesus the pioneer and perfecter of our faith, who for the joy that was set before Him endured the cross, despising the shame, and is seated at the right hand of the throne of God\n\n<i><small>HEBREW 12:2</small></i>`,
  `There is one whose rash words are like sword thrusts, but the tongue of the wise brings healing\n\n<i><small>PROVERBS 12:18</small></i>`,
  `And God is able to provide you with every blessing in abundance, so that you may always have enough of everything and may provide in abundance for every good work\n\n<i><small>2 CORINTHIANS 9:8</small></i>`,
  `I thank my God in all my remembrance of you\n\n<i><small>PHILIPPIANS 1:3</small></i>`,
  `No, in all these things we are more than conquerors through Him who loved us\n\n<i><small>ROMANS 8:37</small></i>`,
  `And when he said this, he breathed on them, and said to them, "Receive the Holy Spirit"\n\n<i><small>JOHN 20:22</small></i>`,
  `For still the vision awaits its time; it hastens to the end-it will not lie. If it seem slow, wait for it; it will surely come, it will not delay\n\n<i><small>HABAKKUK 2:3</small></i>`,
  `For I, the Lord your God, hold your right hand; it is I who say to you, "Fear not, I will help you"\n\n<i><small>ISAIAH 41:13</small></i>`,
  `But I will sing of thy might; I will sing aloud of thy steadfast love in the morning. For thou hast been to me a fortress and a refuge in the day of my distress\n\n<i><small>PSALM 59:16</small></i>`,
  `Therefore if anyone is in Christ, he is a new creation; the old has passed away, behold, the new has come\n\n<i><small>2 CORINTHIANS 5:17</small></i>`,
  `Instead of your shame you shall have a double portion, instead of dishonor you shall rejoice in your lot; therefore in your land you shall possess a double portion;\n\n<i><small>ISAIAH 61:7</small></i>`,
  `For the wages of sin is death, but the free gift of God is eternal life in Christ Jesus our Lord\n\n<i><small>ROMANS 6:23</small></i>`,
  `You are the light of the world. A city set on a hill cannot be hid\n\n<i><small>MATTHEW 5:14</small></i>`,
  `Then Haggai, the messenger of the Lord, spoke to the people with the Lord's message, "I am with you, says the Lord"\n\n<i><small>HAGGAI 1:13</small></i>`,
  `Blessed be the God and Father of our Lord Jesus Christ! By His great mercy we have been born anew to a living hope through the resurrection of Jesus Christ from the dead\n\n<i><small>1 PETER 1:3</small></i>`,
  `Again Jesus spoke to them, saying, "I am the light of the world; he who follows me will not walk in darkness, but will have the light of life"\n\n<i><small>JOHN 8:12</small></i>`,
  `Do not be conformed to this world but be transformed by the renewal of your mind, that you may prove what is the will of God, what is good and acceptable and perfect\n\n<i><small>ROMANS 12:2</small></i>`,
  `Know this, my beloved brethren. Let every man be quick to hear, slow to speak, slow to anger\n\n<i><small>JAMES 1:19</small></i>`,
  `By this we know love, that He laid down His life for us; and we ought to lay down our lives for the brethren\n\n<i><small>1 JOHN 3:16</small></i>`,
  `And we have seen and testify that the Father has sent His son as the Savior of the World\n\n<i><small>1 JOHN 4:14</small></i>`,
  `Whoever confesses that Jesus is the Son of God, God abides in him, and he in God\n\n<i><small>1 JOHN 4:15</small></i>`,
  `There thou art great, O Lord God; for there is none like thee, and there is no God besides thee, according to all that we have heard with our ears\n\n<i><small>2 SAMUEL 7:22</small></i>`,
  `And whatever you do, in word or deed, do everything in the name of the Lord Jesus, giving thanks to God the Father through Him\n\n<i><small>COLOSSIANS 3:17</small></i>`,
  `Wives, be subject to your husbands, as is fitting in the Lord. Husbands, love your wives, and do not be harsh with them\n\n<i><small>COLOSSIANS 3:18-19</small></i>`,
  `Children, obey your parents in everything, for this pleases the Lord\n\n<i><small>COLOSSIANS 3:20</small></i>`,
  `Fathers, do not provoke your children, lest they become discouraged\n\n<i><small>COLOSSIANS 3:21</small></i>`,
  `Slaves, obey in everything those who are your earthly masters, not with eyeservice, as men-pleasers, but in singleness of heart, fearing the Lord\n\n<i><small>COLOSSIANS 3:22</small></i>`,
  `Whatever your task, work heartily, as serving the Lord and not men\n\n<i><small>COLOSSIANS 3:23</small></i>`,
  `Now the Lord is the Spirit, and where the Spirit of the Lord is, there is freedom\n\n<i><small>2 CORINTHIANS 3:17</small></i>`,
  `Have I not commanded you? Be strong and of good courage; be not frightened, neither be dismayed; for the Lord your God is with you wherever you go\n\n<i><small>JOSHUA 1:9</small></i>`,
  `Search me, O God, and know my heart! Try me and know my thoughts!\n\n<i><small>PSALM 139:23</small></i>`,
  `The true light that enlightens every man was coming into the world\n\n<i><small>JOHN 1:9</small></i>`,
  `Forbearing one another and, if one has a complaint against another, forgiving each other; as the Lord has forgiven you, so you also must forgive\n\n<i><small>COLOSSIANS 3:13</small></i>`,
  `Because, if you confess with your lips that Jesus is Lord and believe in your heart that God raised Him from the dead, you will be saved\n\n<i><small>ROMANS 10:9</small></i>`,
  `For man believes with his heart and so is justified, and he confesses with his lips and so is saved\n\n<i><small>ROMANS 10:10</small></i>`,
  `The scripture says, "No one who believes in Him will be put to shame"\n\n<i><small>ROMANS 10:11</small></i>`,
  `In all things I have shown you that by so toiling one must help the weak, remembering the words of the Lord Jesus, how He said, "It is more blessed to give than to receive"\n\n<i><small>ACTS 20:35</small></i>`,
  `By faith we understand that the world was created by the word of God, so that what is seen was made out of things which do not appear\n\n<i><small>HEBREWS 11:3</small></i>`,
  `And without faith it is impossible to please God. For whoever would draw near to God must believe that He exists and He rewards those who seek Him\n\n<i><small>HEBREWS 11:6</small></i>`,
  `The Lord is my strength and my song, and He has become my salvation; this is my God, and I will praise Him, my father's God, and I will exalt Him\n\n<i><small>EXODUS 15:2</small></i>`,
  `But thou, O Lord, art a shield about me, my glory, and the lifter of my head\n\n<i><small>PSALM 3:3</small></i>`,
  `I lie down and sleep; I wake again, for the Lord sustains me\n\n<i><small>PSALM 3:5</small></i>`,
  `Every way of a man is right in his own eyes, but the Lord weighs the heart\n\n<i><small>PROVERBS 21:2</small></i>`,
  `To do righteousness and justice is more acceptable to the Lord than sacrifice\n\n<i><small>PROVERBS 21:3</small></i>`,
  `I write this to you who believe in the name of the Son of God, that you may know that you have eternal life\n\n<i><small>1 JOHN 5:13</small></i>`,
  `And this is the confidence which we have in Him, that if we ask anything according to His will He hears us\n\n<i><small>1 JOHN 5:14</small></i>`,
  `And if we know that He hears us in whatever we ask, we know that we have obtained the requests made of Him\n\n<i><small>1 JOHN 5:15</small></i>`,
  `All wrongdoing is sin, but there is sin which is not mortal\n\n<i><small>1 JOHN 5:17</small></i>`,
  `But thanks be to God, who gives us the victory through our Lord Jesus Christ\n\n<i><small>1 CORINTHIANS 15:57</small></i>`,
  `Therefore, my beloved brethren, be steadfast, immovable, always abounding in the work of the Lord, knowing that in the Lord, your labor is not in vain\n\n<i><small>1 CORINTHIANS 15:58</small></i>`,
  `But when you give alms, do not let your left hand know what your right hand is doing, so that your alms may be in secret; and your Father who sees in secret will reward you\n\n<i><small>MATTHEW 6:3-4</small></i>`,
  `Then He touched their eyes, saying, "According to your faith be it done to you"\n\n<i><small>MATTHEW 9:29</small></i>`,
  `For we walk by faith, not by sight\n\n<i><small>2 CORINTHIANS 5:7</small></i>`,
  `For I am sure that neither death, nor life, nor angels, nor principalities, nor things present, nor things to come, nor powers, nor height, nor depth, nor anything else in all creation, will be able to separate us from the love of God in Christ Jesus our Lord\n\n<i><small>ROMANS 8:38-39</small></i>`,
  `And if I have prophetic powers, and understand all mysteries and all knowledge, and if I have all faith, so as to move mountains, but have not love, I am nothing\n\n<i><small>1 CORINTHIANS 13:2</small></i>`,
  `Love is patient and kind; love is not jealous or boastful; it is not arrogant or rude. Love does not insist on its own way; it is not irritable or resentful\n\n<i><small>1 CORINTHIANS 13:4-5</small></i>`,
  `Love bears all things, believes all things, hopes all things, endures all things\n\n<i><small>1 CORINTHIANS 13:7</small></i>`,
  `Rejoice in the Lord always; again I will say, Rejoice. Let all men know your forbearance. The Lord is at hand\n\n<i><small>PHILIPPIANS 4:4-5</small></i>`,
  `Let love be genuine; hate what is evil, hold fast to what is good; love one another with brotherly affection; outdo one another in showing honor\n\n<i><small>ROMANS 12:9-10</small></i>`,
  `May the Lord give strength to His people! May the Lord bless His people with peace!\n\n<i><small>PSALM 29:11</small></i>`,
  `Fear not, for I am with you, be not dismayed, for I am your God; I will strengthen you, I will help you, I will uphold you with my victorious right hand\n\n<i><small>ISAIAH 41:10</small></i>`,
  `Then my enemies will be turned back in the day when I call. This I know, that God is for me\n\n<i><small>PSALM 56:9</small></i>`,
  `And walk in love, as Christ loved us and gave Himself up for us, a fragrant offering and sacrifice to God\n\n<i><small>EPHESIANS 5:2</small></i>`,
  `I have said this to you, that in me you may have peace. In the world you have tribulation; but be of good cheer, I have overcome the world\n\n<i><small>JOHN 16:33</small></i>`,
  `From the rising of the sun to its setting the name of the Lord is to be praised!\n\n<i><small>PSALM 113:3</small></i>`,
  `The Lord is high above all nations, and His glory above the heavens!\n\n<i><small>PSALM 113:4</small></i>`,
  `Count it all joy, my brethren, when you meet various trials, for you know that the testing of your faith produces steadfastness\n\n<i><small>JAMES 1:2-3</small></i>`,
  `If any of you lacks wisdom, let him ask God, who gives to all men generously and without reproaching, and it will be given him\n\n<i><small>JAMES 1:5</small></i>`,
  `For the mountains may depart and the hills be removed, but my steadfast love shall not depart from you, and my covenant of peace shall not be removed, says the Lord, who has compassion on you\n\n<i><small>ISAIAH 54:10</small></i>`,
  `I know that thou canst do all things, and that no purpose of thine can be thwarted\n\n<i><small>JOB 42:2</small></i>`,
  `When you vow a vow to God, do not delay paying it; for He has no pleasure in fools. Pay what you vow. It is better that you should not vow than that you should vow and not pay\n\n<i><small>ECCLESIASTES 5:4-5</small></i>`,
  `But He was wounded for our transgressions, He was bruised for our iniquities; upon Him was the chastisement that made us whole, and with His stripes we are healed\n\n<i><small>ISAIAH 53:5</small></i>`,
  `But let him ask in faith, with no doubting, for he who doubts is like a wave of the sea that is driven and tossed by the wind\n\n<i><small>JAMES 1:6</small></i>`,
  `Hear this, O Job; stop and consider the wondrous works of God\n\n<i><small>JOB 37:14</small></i>`,
  `So we fasted and besought our God for this, and He listened to our entreaty\n\n<i><small>EZRA 8:23</small></i>`,
  `Even though I walk through the valley of the shadow of death, I fear no evil; for thou art with me; thy rod and thy staff, they comfort me\n\n<i><small>PSALM 23:4</small></i>`,
  `He shall build a house for me, and I will establish His throne forever\n\n<i><small>1 CHRONICLES 17:12</small></i>`,
  `For a day in thy courts is better than a thousand elsewhere. I would rather be a doorkeeper in the  house of my God than dwell in the tents of wickedness\n\n<i><small>PSALM 84:10</small></i>`,
  `For the Lord God is a sun and shield; He bestows favor and honor. No good thing does the Lord withhold from those who walk uprightly\n\n<i><small>PSALM 84:11</small></i>`,
  `O Lord of hosts, blessed is the man who trusts in thee!\n\n<i><small>PSALM 84:12</small></i>`,
  `Behold, God is my salvation; I will trust, and will not be afraid; for the Lord God is my strength and my song, and He has become my salvation\n\n<i><small>ISAIAH 12:2</small></i>`,
  `Then He said to me, "Fear not, Daniel, for from the first day that you set your mind to understand and humbled yourself before your God, your words have been heard, and I have come because of your words"\n\n<i><small>DANIEL 10:12</small></i>`,
  `If my people who are called by my name humble themselves, and pray and seek my face and turn from their wicked ways, then I will hear from heaven, and will forgive their sin and heal their land\n\n<i><small>2 CHRONICLES 7:14</small></i>`,
  `He will swallow up death forever, and the Lord God will wipe away tears from all faces, and the reproach of His people He will take away from all the earth; for the Lord has spoken\n\n<i><small>ISAIAH 25:8</small></i>`,
  `Peace I leave with you; my peace I give to you; not as the world gives do I give to you. Let not your hearts be troubled, neither let them be afraid\n\n<i><small>JOHN 14:27</small></i>`,
  `Then you shall call, and the Lord will answer; you shall cry, and He will say, Here I am.\n\n<i><small>ISAIAH 58:9</small></i>`,
  `To set the mind on the flesh is death, but to set the mind on the Spirit is life and peace\n\n<i><small>ROMANS 8:6</small></i>`,
  `The end of the matter; all has been heard. Fear God, and keep His commandments; for this is the whole duty of man\n\n<i><small>ECCLESIASTES 12:13</small></i>`,
  `For the eyes of the Lord are upon the righteous, and His ears are open to their prayer. But the face of the Lord is against those that do evil\n\n<i><small>1 PETER 3:12</small></i>`,
  `No greater joy can I have than this, to hear that my children follow the truth\n\n<i><small>3 JOHN 1:4</small></i>`,
  `Be strong and of good courage, do not fear or be in dread of them: for it is the Lord your God who goes with you; He will not fail you or forsake you\n\n<i><small>DEUTORONOMY 31:6</small></i>`,
  `For everyone who asks receives, and he who seeks finds, and to him who knocks it will be opened\n\n<i><small>MATTHEW 7:8</small></i>`,
  `Jesus said to him, "I am the way, and the truth, and the life; no one comes to the Father, but by me"\n\n<i><small>JOHN 14:6</small></i>`,
  `And he said to him, "You shall love the Lord your God with all your heart, and with all your soul, and with all your mind"\n\n<i><small>MATTHEW 22:37</small></i>`,
  `I consider that the sufferings of this present time are not worth comparing with the glory that is to be revealed to us\n\n<i><small>ROMANS 8:18</small></i>`,
  `But I say to you that hear, Love your enemies, do good to those who hate you, bless those who curse you, pray for those who abuse you\n\n<i><small>LUKE 6:27-28</small></i>`,
  `O give thanks to the Lord, for He is good; for His steadfast love endures forever!\n\n<i><small>1 CHRONICLES 16:34</small></i>`,
  `Grace to you and peace from God our Father and the Lord Jesus Christ\n\n<i>2 CORINTHIANS 1:2`,
  `Keep your life free from love of money, and be content with what you have; for He has said, "I will never fail you nor forsake you"\n\n<i><small>HEBREWS 13:5</small></i>`,
  `But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness, gentleness and self-control; against such there is no law\n\n<i><small>GALATIANS 5:22-23</small></i>`,
  `Turn back, and say to Hezeki'ah the prince of my people, Thus says the Lord, the God of David your father: I have heard your prayer, I have seen your tears; behold, I will heal you; on the third day you shall go up to the house of the Lord\n\n<i><small>2 KINGS 20:5</small></i>`,
  `Pray constantly\n\n<i><small>1 THESSALONIANS 5:17</small></i>`,
  `Many are the plans in the mind of a man, but it is the purpose of the Lord that will be established\n\n<i><small>PROVERBS 19:21</small></i>`,
  `Take delight in the Lord, and He will give you the desires of your heart\n\n<i>PSALM 37:4`,
  `The Lord your God who goes before you will Himself fight for you, just as He did for you in Egypt before your eyes\n\n<i><small>DEUTERONOMY 1:30</small></i>`,
  `Yes, the Lord will give what is good, and our land will yield its increase\n\n<i><small>PSALM 85:12</small></i>`,
  `Righteousness will go before him, and make his footsteps a way\n\n<i><small>PSALM 85:13</small></i>`,
  `There is none holy like the Lord, there is none besides thee; there is no rock like our God\n\n<i><small>1 SAMUEL 2:2</small></i>`,
  `Have no anxiety about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God\n\n<i><small>PHILIPPIANS 4:6</small></i>`,
  `Better is a dinner of herbs where love is than a fatted ox and hatred with it\n\n<i><small>PROVERBS 15:17</small></i>`,
  `Let not your hearts be troubled; believe in God, believe also in me\n\n<i><small>JOHN 14:1</small></i>`,
  `A gentle tongue is a tree of life, but perverseness in it breaks the spirit\n\n<i><small>PROVERBS 15:4</small></i>`,
  `When you pass through the waters I will be with you; and through the rivers, they shall not overwhelm you; when you walk through fire you shall not be burned, and the flame shall not consume you\n\n<i><small>ISAIAH 43:2</small></i>`,
  `Now faith is the assurance of things hoped for, the conviction of things not seen\n\n<i><small>HEBREWS 11:1</small></i>`,
  `But God shows His love for us in that while we were yet sinners Christ died for us\n\n<i><small>ROMANS 5:8</small></i>`,
  `And be kind to one another, tenderhearted, forgiving one another, as God in Christ forgave you\n\n<i><small>EPHESIANS 4:32</small></i>`,
  `There is no fear in love, but perfect love casts out fear. For fear has to do with punishment, and he who fears is not perfected in love\n\n<i><small>1 JOHN 4:18</small></i>`,
  `We love, because He first loved us\n\n<i><small>1 JOHN 4:19</small></i>`,
  `If anyone says, "I love God," and hates his brother, he is a liar; for he who does not love his brother whom he has seen, cannot love God whom he has not seen\n\n<i><small>1 JOHN 4:20</small></i>`,
  `Beloved, I pray that all may go well with you and that you may be in health; I know that it is well with your soul\n\n<i><small>3 JOHN 1:2</small></i>`,
  `Oil and perfume make the heart glad, but the soul is torn by trouble\n\n<i><small>PROVERBS 27:9</small></i>`,
  `He who blesses his neighbor with a loud voice, rising early in the morning, will be counted as cursing\n\n<i><small>PROVERBS 27:14</small></i>`,
  `There are friends who pretend to be friends, but there is a friend who sticks closer than a brother\n\n<i><small>PROVERBS 18:24</small></i>`,
  `And after you have suffered a little while, the God of all grace, who has called you to His eternal glory in Christ, will Himself restore, establish, and strengthen you\n\n<i><small>1 PETER 5:10</small></i>`,
  `The Lord is a stronghold to him whose way is upright, but destruction to evildoers\n\n<i><small>PROVERBS 10:29</small></i>`,
  `So then, as we have opportunity, let us do good to all men, and especially to those who are of the household of faith\n\n<i><small>GALATIANS 6:10</small></i>`,
  `The grace of the Lord Jesus Christ be with your spirit, brethren. Amen\n\n<i><small>GALATIANS 6:18</small></i>`,
  `The Lord is not slow about His promise as some count slowness, but is forbearing toward you, not wishing that any should perish, but that all should reach repentance\n\n<i><small>2 PETER 3:9</small></i>`,
  `Commit your way to the Lord; trust in Him, and He will act\n\n<i><small>PSALM 37:5</small></i>`,
  `Above all hold unfailing your love for one another, since love covers a multitude of sins\n\n<i><small>1 PETER 4:8</small></i>`,
  `Many are the afflictions of the righteous; but the Lord delivers him out of them all\n\n<i><small>PSALM 34:19</small></i>`,
  `You shall serve the Lord your God, and I will bless your bread and your water; and I will take sickness away from the midst of you\n\n<i><small>EXODUS 23:25</small></i>`,
  `But, as it is written, "What no eye has seen, nor ear heard, nor the heart of man conceived, what God has prepared for those who love Him"\n\n<i><small>1 CORINTHIANS 2:9</small></i>`,
  `For in it the righteousness of God is revealed through faith for faith; as it is written, "He who through faith is righteous shall live."\n\n<i><small>ROMANS 1:17</small></i>`,
  `For I know the plans I have for you, says the Lord, plans for welfare and not for evil, to give you a future and a hope\n\n<i><small>JEREMIAH 29:11</small></i>`,
  `Then you will call upon Me and come and pray to Me, and I will hear you\n\n<i><small>JEREMIAH 29:12</small></i>`,
  `Jesus said to her, "I am the resurrection and the life; he who believes in me, though he die, yet shall he live, and whoever lives and believes in me shall never die. Do you believe this?"\n\n<i><small>JOHN 11:25-26</small></i>`,
  `Rejoice always, pray constantly, give thanks in all circumstances; for this is the will of God in Christ Jesus for you\n\n<i><small>1 THESSALONIANS 5:16-18</small></i>`,
  `The Lord is good, a stronghold in the day of trouble; He knows those who take refuge in Him\n\n<i><small>NAHUM 1:7</small></i>`,
  `No evil shall befall you, no scourge come near your tent. For He will give His angels charge of you to guard you in all your ways\n\n<i><small>PSALMS 91:10-11</small></i>`,
  `"Yet even now," says the Lord, "return to me with all your heart, with fasting, with weeping, and with mourning;"\n\n<i><small>JOEL 2:12</small></i>`,
  `After these things the word of the Lord came to Abram in a vision, "Fear not, Abram, I am your shield; your reward shall be very great"\n\n<i><small>GENESIS 15:1</small></i>`,
  `Awaiting our blessed hope, the appearing of the glory of our great God and Savior Jesus Christ\n\n<i><small>TITUS 2:13</small></i>`,
  `The righteous will never be removed, but the wicked will not dwell in the land\n\n<i><small>PROVERBS 10:30</small></i>`,
  `Behold, I am with you and will keep you wherever you go, and will bring you back to this land; for I will not leave you until I have done that of which I have spoken to you\n\n<i><small>GENESIS 28:15</small></i>`,
  `But He said to me, "My grace is sufficient for you, for my power is made perfect in weakness." I will all the more gladly boast of my weaknesses, that the power of Christ may rest upon me\n\n<i><small>2 CORINTHIANS 12:9</small></i>`,
  `And He said to them, "Take heed, and beware of all covetousness; for a man's life does not consist in abundance of his possessions"\n\n<i><small>LUKE 12:15</small></i>`,
  `Thou art my hiding place and my shield; I hope in thy word\n\n<i><small>PSALM 119:114</small></i>`,
  `Can a woman forget her sucking child, that she should have no compassion on the son of her womb? Even these may forget, yet I will not forget you\n\n<i><small>ISAIAH 49:15</small></i>`,
  `Be not afraid of them, for I am with you to deliver you, says the Lord\n\n<i><small>JEREMIAH 1:8</small></i>`,
  `Commit your work to the Lord, and your plans will be established\n\n<i><small>PROVERBS 16:3</small></i>`,
  `When a man's ways please the Lord, He makes even his enemies to be at peace with him\n\n<i><small>PROVERBS 16:7</small></i>`,
  `Better is a little with righteousness than great revenues with injustice\n\n<i><small>PROVERBS 16:8</small></i>`,
  `Hence I remind you to rekindle the gift of God that is within you through the laying on of my hands\n\n<i><small>2 TIMOTHY 1:6</small></i>`,
  `O come, let us sing to the Lord; let us make a joyful noise to the rock of our salvation!\n\n<i><small>PSALM 95:1</small></i>`,
  `Let brotherly love continue\n\n<i><small>HEBREWS 13:1</small></i>`,
  `Do not neglect to show hospitality to strangers, for thereby some have entertained angels unawares\n\n<i><small>HEBREWS 13:2</small></i>`,
  `Hence we can confidently say, "The Lord is my helper, I will not be afraid; what can man do to me?"\n\n<i><small>HEBREWS 13:6</small></i>`,
  `Judge not, and you will not be judged; condemn not, and you will not be condemned; forgive, and you will be forgiven;\n\n<i><small>LUKE 6:37</small></i>`,
  `Do not be deceived; God is not mocked, for whatever a man sows, that he will also reap\n\n<i><small>GALATIANS 6:7</small></i>`,
  `And let us not grow weary in well-doing, for in due season we shall reap, if we do not lose heart\n\n<i><small>GALATIANS 6:9</small></i>`,
  `Wait for the Lord; be strong, and let your heart take courage; yes, wait for the Lord!\n\n<i><small>PSALM 27:14</small></i>`,
  `The Lord is just in all His ways, and kind in all His doings\n\n<i><small>PSALM 145:17</small></i>`,
  `The Lord is near to all who call upon Him, to all who call upon Him in truth\n\n<i><small>PSALM 145:18</small></i>`,
  `On the glorious splendor of thy majesty, and on thy wondrous works, I will meditate\n\n<i><small>PSALM 145:5</small></i>`,
  `Remember the wonderful works that He has done, His miracles, and the judgments He uttered\n\n<i><small>PSALM 105:5</small></i>`,
  `And the peace of God, which passes all understanding, will keep your hearts and your minds in Christ Jesus\n\n<i><small>PHILIPPIANS 4:7</small></i>`,
  `Two are better than one, because they have a good reward for their toil\n\n<i><small>ECCLESIASTES 4:9</small></i>`,
  `Ask, and it will be given to you; seek, and you will find; knock, and it will be opened to you\n\n<i><small>MATTHEW 7:7</small></i>`,
  `Wisdom builds her house, but folly with her own hands tears it down\n\n<i><small>PROVERBS 14:1</small></i>`,
  `Leave the presence of a fool, for there you do not meet words of knowledge\n\n<i><small>PROVERBS 14:7</small></i>`,
  `He has made everything beautiful in its time; also He has put eternity into man's mind, yet so that he cannot find out what God has done from the beginning to the end\n\n<i><small>ECCLESIASTES 3:11</small></i>`,
  `He who forgives an offense seeks love, but he who repeats a matter alienates a friend\n\n<i><small>PROVERBS 17:9</small></i>`,
  `O give thanks to the Lord, for He is good; for His steadfast love endures forever!\n\n<i><small>PSALM 107:1</small></i>`,
  `But to all who received Him, who believed in His name, He gave power to become children of God;\n\n<i><small>JOHN 1:12</small></i>`,
  `And the Word became flesh and dwelt among us, full of grace and truth; we have beheld His glory, glory as of the only Son from the Father\n\n<i><small>JOHN 1:14</small></i>`,
  `O Lord, let thy ear be attentive to the prayer of thy servant, and to the prayer of thy servants who delight to fear thy name; and give success to thy servant today, and grant him mercy in the sight of this man\n\n<i><small>NEHEMIAH 1:11</small></i>`,
  `And they said, "Believe in the Lord Jesus, and you will be saved, you and your household"\n\n<i><small>ACTS 16:31</small></i>`,
  `The steadfast love of the Lord never ceases, His mercies never come to an end; they are new every morning; great is thy faithfulness\n\n<i><small>LAMENTATIONS 3:22-23</small></i>`,
  `It is good that one should wait quietly for the salvation of the Lord\n\n<i><small>LAMENTATIONS 3:26</small></i>`,
  `The end of all things is at hand; therefore keep sane and sober for your prayers\n\n<i><small>1 PETER 4:7</small></i>`,
  `Cast your burden on the Lord, and He will sustain you; He will never permit the righteous to be moved\n\n<i><small>PSALM 55:22</small></i>`,
  `Practice hospitality ungrudgingly to one another\n\n<i><small>1 PETER 4:9</small></i>`,
  `My beloved is mine and I am his, he pastures his flock among the lilies\n\n<i><small>SONG OF SOLOMON 2:16</small></i>`,
  `And above all these put on love, which binds everything together in perfect harmony\n\n<i><small>COLOSSIANS 3:14</small></i>`,
  `Little children, let us not love in word or speech but in deed and in truth\n\n<i><small>1 JOHN 3:18</small></i>`,
  `Be watchful, stand firm in your faith, be courageous, be strong\n\n<i><small>1 CORINTHIANS 16:13</small></i>`,
  `Let all that you do be done in love\n\n<i><small>1 CORINTHIANS 16:14</small></i>`,
  `A cheerful heart is a good medicine, but a downcast spirit dries up the bones\n\n<i><small>PROVERBS 17:22</small></i>`,
  `A wicked man accepts a bribe from the bosom to pervert the ways of justice\n\n<i><small>PROVERBS 17:23</small></i>`,
  `For God so loved the world that He gave His only Son, that whoever believes in Him should not perish but have eternal life\n\n<i><small>JOHN 3:16</small></i>`,
  `The Lord appeared to him from afar. I have loved you with an everlasting love; therefore I have continued my faithfulness to you\n\n<i><small>JEREMIAH 31:3</small></i>`,
  `To aspire to live quietly, to mind your own affairs, and to work with your hands, as we charged you;\n\n<i><small>1 THESSALONIANS 4:11</small></i>`,
  `But ignoring what they said, Jesus said to the ruler of the synagogue, "Do not fear, only believe"\n\n<i><small>MARK 5:36</small></i>`,
  `Be strong, and let your heart take courage, all you who wait for the Lord!\n\n<i><small>PSALM 31:24</small></i>`,
  `I will instruct you and teach you the way you should go; I will counsel you with my eye upon you\n\n<i><small>PSALM 32:8</small></i>`,
  `Therefore, my beloved, as you have always obeyed, so now, not only as in my presence but much more in my absence, work out your own salvation with fear and trembling\n\n<i><small>PHILIPPIANS 2:12</small></i>`,
  `Do all things without grumbling or questioning, that you may be blameless and innocent, children of God without blemish in the midst of a crooked and perverse generation, among whom you shine as lights in the world\n\n<i><small>PHILIPPIANS 2:14-15</small></i>`,
  `Him we proclaim, warning every man and teaching every man in all wisdom, that we may present every man mature in Christ\n\n<i><small>COLOSSIANS 1:28</small></i>`,
  `Be not quick to anger, for anger lodges in the bosom of fools\n\n<i><small>ECCLESIASTES 7:9</small></i>`,
  `Better is the end of a thing than its beginning; and the patient in spirit is better than the proud in spirit\n\n<i><small>ECCLESIASTES 7:8</small></i>`,
  `For the protection of wisdom is like the protection of money; and the advantage of knowledge is that wisdom preserves the life of him who has it\n\n<i><small>ECCLESIASTES 7:12</small></i>`,
  `Though a sinner does evil a hundred times and prolongs his life, yet I know that it will be well with those who fear God, because they fear before Him\n\n<i><small>ECCLESIASTES 8:12</small></i>`,
  `O Lord, thou art my God; I will exalt thee, I will praise thy name; for thou hast done wonderful things, plans formed of old, faithful and sure\n\n<i><small>ISAIAH 25:1</small></i>`,
  `Beloved, let us love one another; for love is of God, and he who loves is born of God and knows God\n\n<i><small>1 JOHN 4:7</small></i>`,
  `He who does not love does not know God; for God is love\n\n<i><small>1 JOHN 4:8</small></i>`,
  `My eyes are ever toward the Lord, for He will pluck my feet out of the net\n\n<i><small>PSALM 25:15</small></i>`,
  `The fear of man lays a snare, but he who trusts in the Lord is safe\n\n<i><small>PROVERBS 29:25</small></i>`,
  `He who heeds instruction is on the path to life, but he who rejects reproof goes astray\n\n<i><small>PROVERBS 10:17</small></i>`,
  `My help comes from the Lord, who made heaven and earth\n\n<i><small>PSALM 121:2</small></i>`,
  `The Lord is near to the brokenhearted, and saves the crushed in spirit\n\n<i><small>PSALM 34:18</small></i>`,
  `Father of the fatherless and protector of widows is God in his holy habitation\n\n<i><small>PSALM 68:5</small></i>`,
  `This is the day which the Lord has made; let us rejoice and be glad in it\n\n<i><small>PSALM 118:24</small></i>`,
  `A new commandment I give to you, that you love one another; even as I have loved you, that you also love one another\n\n<i><small>JOHN 13:34</small></i>`,
  `May the God of steadfastness and encouragement grant you to live in such harmony with one another, in accord with Christ Jesus\n\n<i><small>ROMANS 15:5</small></i>`,
  `That together you may with one voice glorify the God and Father of our Lord Jesus Christ\n\n<i><small>ROMANS 15:6</small></i>`,
  `Let your speech always be gracious, seasoned with salt, so that you may know how you ought to answer everyone\n\n<i><small>COLOSSIANS 4:6</small></i>`,
  `I love the Lord, because He has heard my voice and my supplications\n\n<i><small>PSALM 116:1</small></i>`,
  `Because He inclined His ear to me, therefore I will call on Him as long as I live\n\n<i><small>PSALM 116:2</small></i>`,
  `Gracious is the Lord, and righteous; our God is merciful\n\n<i><small>PSALM 116:5</small></i>`,
  `What shall I render to the Lord for all His bounty to me?\n\n<i><small>PSALM 116:12</small></i>`,
  `So Jacob served seven years for Rachel, and they seemed to him but a few days because of the love he had for her\n\n<i><small>GENESIS 29:20</small></i>`,
  `For with God nothing will be impossible\n\n<i><small>LUKE 1:37</small></i>`,
  `And Mary said, "Behold, I am the handmaid of the Lord; let it be done to me according to your word." And the angel departed from her\n\n<i><small>LUKE 1:38</small></i>`,
  `Moreover choose able men from all the people, such as fear God, men who are trustworthy and who hate a bribe; and place such men over the people as rulers of thousands, of hundreds, of fifties, and of tens\n\n<i><small>EXODUS 18:21</small></i>`,
  `And He said, "My presence will go with you, and I will give you rest."\n\n<i><small>EXODUS 33:14</small></i>`,
  `And a cloud overshadowed them, and a voice came out of the cloud, "This is my beloved Son; listen to Him."\n\n<i><small>MARK 9:7</small></i>`,
  `Anxiety in a man's heart weighs him down, but a good word makes him glad\n\n<i><small>PROVERBS 12:25</small></i>`,
  `A slothful man will not catch his prey, but the diligent man will get precious wealth\n\n<i><small>PROVERBS 12:27</small></i>`,
  `The people who walked on darkness have seen a great light; those who dwelt in a land of deep darkness, on them has light shined\n\n<i><small>ISAIAH 9:2</small></i>`,
  `And when I go and prepare a place for you, I will come again and will take you to myself, that where I am you may also be\n\n<i><small>JOHN 14:3</small></i>`,
  `For where two or three are gathered in my name, there am I in the midst of them\n\n<i><small>MATTHEW 18:20</small></i>`,
  `But He gives more grace; therefore it says, "God opposes the proud, but gives grace to the humble"\n\n<i><small>JAMES 4:6</small></i>`,
  `Submit yourselves therefore to God. Resist the devil and he will flee from you\n\n<i><small>JAMES 4:7</small></i>`,
  `Draw near to God and He will draw near to you. Cleanse your hands, you sinners, and purify your hearts, you men of double mind\n\n<i><small>JAMES 4:8</small></i>`,
  `Humble yourselves before the Lord and He will exalt you\n\n<i><small>JAMES 4:10</small></i>`,
  `There is one lawgiver and judge, He who is able to save and to destroy. But who are you that you judge your neighbor?\n\n<i><small>JAMES 4:12</small></i>`,
  `Whereas you do not know about tomorrow. What is your life? For you are a mist that appears for a little time and then vanishes\n\n<i><small>JAMES 4:14</small></i>`,
  `I thank my God always when I remember you in my prayers\n\n<i><small>PHILEMON 1:4</small></i>`,
  `And I pray that the sharing of your faith may promote the knowledge of all the good that is ours in Christ\n\n<i><small>PHILEMON 1:6</small></i>`,
  `The Rock, His work is perfect; for all His ways are justice. A God of faithfulness and without inquity, just and right is He\n\n<i><small>DEUTERONOMY 32:4</small></i>`,
  `But I do not account my life of any value nor as precious to myself, if only I may accomplish my course and the ministry which I received from the Lord Jesus, to testify to the gospel of the grace of God\n\n<i><small>ACTS 20:24</small></i>`,
  `Truly, I say to you, whoever does not receive the kingdom of God like a child shall not enter it\n\n<i><small>LUKE 18:17</small></i>`,
  `But in your hearts reverence Christ as Lord. Always be prepared to make a defense to anyone who calls you to account for the hope that is in you, yet do it with gentleness and reverence;\n\n<i><small>1 PETER 3:15</small></i>`,
  `Do you not know that you are God's temple and that God's Spirit dwells in you?\n\n<i><small>1 CORINTHIANS 3:16</small></i>`,
  `If anyone destroys God's temple, God will destroy him. For God's temple is holy, and that temple you are\n\n<i><small>1 CORINTHIANS 3:17</small></i>`,
  `And you are Christ's; and Christ is God's\n\n<i><small>1 CORINTHIANS 3:23</small></i>`,
  `For the desires of the flesh are against the Spirit, and the desires of the Spirit are against the flesh; for these are opposed to each other, to prevent you from doing what you would\n\n<i><small>GALATIANS 5:17</small></i>`,
  `Look carefully then how you walk, not as unwise men but as wise, making the most of the time, because the days are evil\n\n<i><small>EPHESIANS 5:15-16</small></i>`,
  `Therefore do not be foolish, but understand what the will of the Lord is\n\n<i><small>EPHESIANS 5:17</small></i>`,
  `Because we are members of His body\n\n<i><small>EPHESIANS 5:30</small></i>`,
  `But there are also many other things which Jesus did; were every one of them to be written, I suppose that the world itself could not contain the books that would be written\n\n<i><small>JOHN 21:25</small></i>`,
  `Answer me when I call, O God of my right! Thou hast given me room when I was in distress. Be gracious to me, and hear my payer\n\n<i><small>PSALM 4:1</small></i>`,
  `The Lord is good to those who wait for Him, to the soul that seeks Him. It is good that one should wait quietly for the salvation of the Lord\n\n<i><small>LAMENTATIONS 3:25-26</small></i>`,
  `Let us test and examine our ways, and return to the Lord!\n\n<i><small>LAMENTATIONS 3:40</small></i>`,
  `For righteousness is immortal\n\n<i><small>WISDOM OF SOLOMON 1:15</small></i>`,
  `If riches are a desirable possessions in life, what is richer than wisdom who effects all things?\n\n<i><small>WISDOM OF SOLOMON 8:5</small></i>`,
  `You are all fair, my love; there is no flaw in you\n\n<i><small>SONG OF SOLOMON 4:7</small></i>`,
  `Even as the Son of man came not to be served but to serve, and to give His life as a ransom for many\n\n<i><small>MATTHEW 20:28</small></i>`,
  `Jesus Christ is the same yesterday and today and forever\n\n<i><small>HEBREWS 13:8</small></i>`,
  `And my God will supply every need of yours according to His riches in glory in Christ Jesus\n\n<i><small>PHILIPPIANS 4:19</small></i>`,
  `For my thoughts are not your thoughts, neither are your ways my ways, says the Lord\n\n<i><small>ISAIAH 55:8</small></i>`,
  `That your faith might not rest in the wisdom of men, but in the power of God\n\n<i><small>1 CORINTHIANS 2:5</small></i>`,
  `And he will be the stability of your times, abundance of salvation, wisdom, and knowledge; the fear of the Lord is his treasure\n\n<i><small>ISAIAH 6:33</small></i>`,
  `You will tread on the lion and the adder, the young lion and the serpent you will trample under foot. Because he cleaves to me in love, I will deliver him; I will protect him, because he knows my name\n\n<i><small>PSALMS 91:13-14</small></i>`,
  `But now put them all away: anger, wrath, malice, slander, and foul talk from your mouth\n\n<i><small>COLOSSIANS 3:9</small></i>`,
  `He must increase, but I must decrease\n\n<i><small>JOHN 3:30</small></i>`,
  `Repay no one evil for evil, but take thought for what is noble in the sight of all\n\n<i><small>ROMANS 12:17</small></i>`,
  `There is a great gain in godliness with contentment\n\n<i><small>1 TIMOTHY 6:6</small></i>`,
  `If a widow has children or grandchildren, let them first learn their religious duty to their own family and make some return to their parents; for this is acceptable in the sight of God\n\n<i><small>1 TIMOTHY 5:4</small></i>`,
  `I have fought the good fight, I have finished the race, I have kept the faith\n\n<i><small>2 TIMOTHY 4:7</small></i>`,
  `But of that day or that hour no one knows, not even the angels in heaven, nor the Son, but only the Father\n\n<i><small>MARK 13:32</small></i>`,
  `The Lord will fight for you, and you have only to be still\n\n<i><small>EXODUS 14:14</small></i>`,
  `Arise, for it is your task, and we are with you; be strong and do it\n\n<i><small>EZRA 10:4</small></i>`,
  `Why are you cast down, O my soul, and why are you disquieted within me? Hope in God; for I shall again praise Him, my help and my God\n\n<i><small>PSALM 42:11</small></i>`,
  `Being therefore exalted at the right hand of God, and having received from the Father the promise of the Holy Spirit, He has poured out this which you see and hear\n\n<i><small>ACTS 2:33</small></i>`,
  `Remember the word that I said to you, "A servant is not greater than his master". If they persecuted me, they will persecute you; if they kept my word, they will keep yours also\n\n<i><small>JOHN 15:20</small></i>`,
  `He who hates me hates my Father also\n\n<i><small>JOHN 15:23</small></i>`,
  `And you also are witnesses, because you have been with me from the beginning\n\n<i><small>JOHN 15:27</small></i>`,
  `No greater joy can I have than this, to hear that my children follow the truth\n\n<i><small>3 JOHN 1:4</small></i>`,
  `For it is God's will that by doing right you should put to silence the ignorance of foolish men\n\n<i><small>1 PETER 2:15</small></i>`,
  `So there will be richly provided for you an entrance into the eternal kingdom of our Lord and Savior Jesus Christ\n\n<i><small>2 PETER 1:11</small></i>`,
  `You came near when I called you, and you said, "Do not fear"\n\n<i><small>LAMENTATIONS 3:57</small></i>`,
  `I know that there is nothing better for them than to be happy and enjoy themselves as long as they live\n\n<i><small>ECCLESIASTES 3:12</small></i>`,
  `Also that it is God's gift to man that everyone should eat and drink and take pleasure in all his toil\n\n<i><small>ECCLESIASTES 3:13</small></i>`,
  `I am with you always, to the close of the age\n\n<i><small>MATTHEW 28:20</small></i>`,
  `But let it be the hidden person of the heart with the imperishable jewel of a gentle and quiet spirit, which in God's sight is very precious\n\n<i><small>1 PETER 3:4</small></i>`,
  `Therefore do not be anxious about tomorrow, for tomorrow will be anxious for itself. Let the day's own trouble be sufficient for the day\n\n<i><small>MATTHEW 6:34</small></i>`,
  `And Jesus said to him, "If you can! All things are possible to him who believes\n\n<i><small>MARK 9:23</small></i>`,
  `Even to your old age I am He, and to gray hairs I will carry you. I have made, and I will bear; I will carry and will save\n\n<i><small>ISAIAH 46:4</small></i>`,
  `But by the grace of God I am what I am, and His grace toward me was not in vain. On the contrary, I worked harder than any of them, though it was not I, but the grace of God which is with me\n\n<i><small>1 CORINTHIANS 15:10</small></i>`,
  `He who walks with wise men becomes wise, but the companion of fools will suffer harm\n\n<i><small>PROVERBS 13:20</small></i>`,
  `Misfortune pursues sinners, but prosperity rewards the righteous\n\n<i><small>PROVERBS 13:21</small></i>`,
  `Do not be deceived: "Bad company ruins good morals"\n\n<i><small>1 CORINTHIANS 15:33</small></i>`,
  `Come to your right mind, and sin no more. For some have no knowledge of God. I say this to your shame\n\n<i><small>1 CORINTHIANS 15:34</small></i>`,
  `But thanks be to God, who gives us the victory through our Lord Jesus Christ\n\n<i><small>1 CORINTHIANS 15:57</small></i>`,
  `Therefore take the whole armor of God, that you may be able to withstand in the evil day, and having done all, to stand\n\n<i><small>EPHESIANS 6:13</small></i>`,
  `But He withdrew to the wilderness and prayed\n\n<i><small>LUKE 5:16</small></i>`,
  `Everyone then who hears these words of mine and does them will be like a wise man who built his house upon the rock\n\n<i><small>MATTHEW 7:24</small></i>`,
  `For if you forgive men their trespasses, your heavenly Father also will forgive you\n\n<i><small>MATTHEW 6:14</small></i>`,
  `Do not lay up for yourselves treasures on earth, where moth and rust consume and where thieves break in and steal, but lay up for yourselves treasures in heaven, where neither moth or rust consumes and where thieves do not break in and steal\n\n<i><small>MATTHEW 6:19-20</small></i>`,
  `The eye is the lamp of the body. So, if your eye is sound, your whole body will be full of light\n\n<i><small>MATTHEW 6:22</small></i>`,
  `And why are you anxious about clothing? Consider the lilies of the field, how they grow; they neither toil nor spin\n\n<i><small>MATTHEW 6:28</small></i>`,
  `All scripture is inspired by God and profitable for teaching, for reproof, for correction, and for training in righteousness, that the man of God may be complete, equipped for every good work\n\n<i><small>2 TIMOTHY 3:16-17</small></i>`,
  `But he said, "What is impossible with men is possible with God"\n\n<i><small>LUKE 18:27</small></i>`,
  `Thy word is a lamp to my feet and a light to my path\n\n<i><small>PSALM 119:105</small></i>`,
  `I am sorely afflicted; give me life, O Lord, according to thy word!\n\n<i><small>PSALM 119:107</small></i>`,
  `Just so, I tell you, there will be more joy in heaven over one sinner who repents than over ninety-nine righteous persons who need no repentance\n\n<i><small>LUKE 15:7</small></i>`,
  `For the weapons of our warfare are not worldly but have divine power to destroy strongholds\n\n<i><small>2 CORINTHIANS 10:4</small></i>`,
  `As for the man who is weak in faith, welcome him, but not for disputes over opinions\n\n<i><small>ROMANS 14:1</small></i>`,
  `None of us lives to himself, and none of us dies to himself\n\n<i><small>ROMANS 14:7</small></i>`,
  `Then let us no more pass judgment on one another, but rather decide never to put a stumbling block or hindrance in the way of a brother\n\n<i><small>ROMANS 14:13</small></i>`,
  `For the kingdom of God does not mean food and drink but righteousness and peace and joy in the Holy Spirit\n\n<i><small>ROMANS 14:17</small></i>`,
  `But he who is united to the Lord becomes one spirit with Him\n\n<i><small>1 CORINTHIANS 6:17</small></i>`,
  `Do you not know that your body is a temple of the Holy Spirit within you, which you have from God? You are not your own; you were bought with a price. So glorify God in your body!\n\n<i><small>1 CORINTHIANS 6:19-20</small></i>`,
  `But each person is tempted when he is lured and enticed by his own desire. Then desire when it has conceived gives birth to sin; and sin when it is full-grown brings forth death\n\n<i><small>JAMES 1:14-15</small></i>`,
  `Sanctify them in the truth; thy word is truth\n\n<i><small>JOHN 17:17</small></i>`,
  `See what love the Father has given us, that we should be called children of God; and so we are. The reason why the world does not know us is that it did not know Him\n\n<i><small>1 JOHN 3:1</small></i>`,
  `Beloved, we are God's children now; it does not yet appear what we shall be, but we know that when He appears we shall be like Him, for we shall see Him as He is\n\n<i><small>1 JOHN 3:2</small></i>`,
  `For this is the message which you have heard from the beginning, that we should love one another\n\n<i><small>1 JOHN 3:11</small></i>`,
  `And this is His commandment, that we should believe in the name of His Son Jesus Christ and love one another, just as He has commanded us\n\n<i><small>1 JOHN 3:23</small></i>`,
  `Blessed be the God and Father of our Lord Jesus Christ, who has blessed us in Christ with every spiritual blessing in the heavenly places\n\n<i><small>EPHESIANS 1:3</small></i>`,
  `I will not leave you desolate; I will come to you\n\n<i><small>JOHN 14:18</small></i>`,
  `This I command you, to love one another\n\n<i><small>JOHN 15:17</small></i>`,
  `Let all bitterness and wrath and anger and clamor and slander be put away from you, with all malice\n\n<i><small>EPHESIANS 4:31</small></i>`,
  `It is sown in dishonor, it is raised in glory. It is sown in weakness, it is raised in power. It is sown a physical body, it is raised a spiritual body. If there is a physical body, there is also a spiritual body\n\n<i><small>1 CORINTHIANS 15:43-44</small></i>`,
  `I waited patiently for the Lord; He inclined to me and heard my cry. He drew me up from the desolate pit, out of the miry bog, and set my feet upon a rock, making my steps secure\n\n<i><small>PSALMS 40:1-2</small></i>`,
  `Husbands, love your wives, as Christ loved the church and gave Himself up for her\n\n<i><small>EPHESIANS 5:25</small></i>`,
  `Even so husbands should love their wives as their own bodies. He who loves his wife loves himself\n\n<i><small>EPHESIANS 5:28</small></i>`,
  `Wives, be subject to your husbands, as to the Lord\n\n<i><small>EPHESIANS 5:22</small></i>`,
  `From the same mouth come blessing and cursing. My brethren, this ought not to be so\n\n<i><small>JAMES 3:10</small></i>`,
  `But the wisdom from above is first pure, then peaceable, gentle, open to reason, full of mercy and good fruits, without uncertainty or insincerity\n\n<i><small>JAMES 3:17</small></i>`,
  `And the harvest of righteousness is sown in peace by those who make peace\n\n<i><small>JAMES 3:18</small></i>`,
  `So shun youthful passions and aim at righteousness, faith, love, and peace, along with those who call upon the Lord from a pure heart\n\n<i><small>2 TIMOTHY 2:22</small></i>`,
  `But you shall receive power when the Holy Spirit has come upon you; and you shall be my witnesses in Jerusalem and in all Judea and Samar'ia and to the end of the earth\n\n<i><small>ACTS 1:8</small></i>`,
  `So neither he who plants nor he who waters is anything, but only God who gives the growth\n\n<i><small>1 CORINTHIANS 3:7</small></i>`,
  `And the priest said to them, "Go in peace. The journey in which you go is under the eye of the Lord"\n\n<i><small>JUDGES 18:6</small></i>`,
  `Bless the Lord, O my soul; and all that is within me, bless His holy name!\n\n<i><small>PSALM 103:1</small></i>`,
  `For He is our peace, who has made us both one, and has broken down the dividing wall of hostility\n\n<i><small>EPHESIANS 2:14</small></i>`,
  `Surely oppression makes the wise man foolish, and a bribe corrupts the mind\n\n<i><small>ECCLESIASTES 7:7</small></i>`,
  `Be not righteous overmuch, and do not make yourself overwise; why should you destroy yourself?\n\n<i><small>ECCLESIASTES 7:16</small></i>`,
  `Be not wicked overmuch, neither be a fool; why should you die before your time?\n\n<i><small>ECCLESIASTES 7:17</small></i>`,
  `Wisdom gives strength to the wise man more than ten rulers that are in a city\n\n<i><small>ECCLESIASTES 7:19</small></i>`,
  `All this I have tested by wisdom; I said, "I will be wise"; but it was far from me\n\n<i><small>ECCLESIASTES 7:23</small></i>`,
  `He who finds his life will lose it, and he who loses his life for My sake will find it\n\n<i><small>MATTHEW 10:39</small></i>`,
  `Be not exceedingly angry, O Lord, and remember not iniquity forever. Behold, consider, we are all thy people\n\n<i><small>ISAIAH 64:9</small></i>`,
  `Light rises in the darkness for the upright; the Lord is gracious, merciful and righteous\n\n<i><small>PSALM 112:4</small></i>`,
  `He is not afraid of evil tidings; his heart is firm, trusting in the Lord\n\n<i><small>PSALM 112:7</small></i>`,
  `And He died for all, that those who live might live no longer for themselves but for Him who for their sake died and was raised\n\n<i><small>2 CORINTHIANS 5:15</small></i>`,
  `Create in me a clean heart, O God, and put a new and right spirit within me\n\n<i><small>PSALM 51:10</small></i>`,
  `Likewise the Spirit helps us in our weakness; for we do not know how to pray as we ought, but the Spirit himself intercedes for us with sighs too deep for words\n\n<i><small>ROMANS 8:26</small></i> `,
  `And he who searches the hearts of men knows what is the mind of the Spirit, because the Spirit intercedes for the saints according to the will of God\n\n<i><small>ROMANS 8:27</small></i>`,
  `There is great gain in godliness with contentment\n\n<i><small>1 TIMOTHY 6:6</small></i>`,
  `For we brought nothing into the world, and we cannot take anything out of the world; but if we have food and clothing, with these we shall be content\n\n<i><small>1 TIMOTHY 6:7-8</small></i>`,
  `For the love of money is the root of all evils; it is through this craving that some have wandered away from the faith and pierced their hearts with many pangs\n\n<i><small>1 TIMOTHY 6:10</small></i>`,
  `But as for you, man of God, shun all this; aim at righteousness, godliness, faith, love, steadfastness, gentleness\n\n<i><small>1 TIMOTHY 6:11</small></i>`,
  `Fight the good fight of the faith; take hold of the eternal life to which you were called when you made the good confession in the presence of many witnesses\n\n<i><small>1 TIMOTHY 6:12</small></i>`,
  `And it shall be that whoever calls in the name of the Lord shall be saved\n\n<i><small>ACTS 2:21</small></i>`,
  `Before I formed you in the womb I knew you, and before you were born I consecrated you; I appointed you a prophet to the nations\n\n<i><small>JEREMIAH 1:5</small></i>`,
  `If one gives answer before he hears, it is his folly and shame\n\n<i><small>PROVERBS 18:13</small></i>`,
  `Let each of you look not only to his own interests, but also to the interests of others\n\n<i><small>PHILIPPIANS 2:4</small></i>`,
  `For lo, the winter is past, the rain is over and gone. The flowers appear on the earth, the time of singing has come, and the voice of the turtledove is heard in our land\n\n<i><small>SONG OF SOLOMON 2:11-12</small></i>`,
  `As for the saints in the land, they are the noble, in whom is all my delight\n\n<i><small>PSALM 16:3</small></i>`,
  `And the dust returns to the earth as it was, and the spirit returns to God who gave it\n\n<i><small>ECCLESIASTES 12:7</small></i>`,
  `Vanity of vanities, says the preacher; all is vanity\n\n<i><small>ECCLESIASTES 12:8</small></i>`,
  `He who tills his land will have plenty of bread, but he who follows worthless pursuits will have plenty of poverty\n\n<i><small>PROVERBS 28:19</small></i>`,
  `Return to your stronghold, O prisoners of hope; today I declare that I will restore you to double\n\n<i><small>ZECHARIAH 9:12</small></i>`,
  `For the needy shall not always be forgotten, and the hope of the poor shall not perish forever\n\n<i><small>PSALM 9:18</small></i>`,
  `For you shall go out in joy, and be led forth in peace; the mountains and the hills before you shall break forth into singing, and all the trees of the field shall clap their hands\n\n<i><small>ISAIAH 55:12</small></i>`,
  `But as for me, I will look to the Lord, I will wait for the God of the salvation; My God will hear me\n\n<i><small>MICAH 7:7</small></i>`,
  `But we are not of those who shrink back and are destroyed, but of those who have faith and keep their souls\n\n<i><small>HEBREWS 10:39</small></i>`,
  `For you have need of endurance, so that you may do the will of God and receive what is promised\n\n<i><small>HEBREWS 10:36</small></i>`,
  `May the Lord make you increase and abound in love for one another and for all, at the coming of our Lord Jesus with all His holy ones\n\n<i><small>1 THESSALONIANS 3:12-13</small></i>`,
  `Blessed is the man who endures trial, for when he has stood the test he will receive the crown of life which God has promised to those who love Him\n\n<i><small>JAMES 1:12</small></i>`,
  `He leads the humble in what is right, and teaches the humble his way\n\n<i><small>PSALM 25:9</small></i>`,
  `Every valley shall be filled, and every mountain and hill shall be brought low, and the crooked shall be made straight, and the rough ways shall be made smooth\n\n<i><small>LUKE 3:5-6</small></i>`,
  `Do not neglect to do good and to share what you have, for such sacrifices are pleasing to God\n\n<i><small>HEBREWS 13:16</small></i>`,
  `You will decide on a matter, and it will be established for you, and light will shine on your ways\n\n<i><small>JOB 22:28</small></i>`,
  `And from His fullness have we all received, grace upon grace\n\n<i><small>JOHN 1:16</small></i>`,
  `In the day of prosperity be joyful, and in the day of adversity consider; God has made the one as well as the other, so that man may not find out anything that will be after him\n\n<i><small>ECCLESIASTES 7:14</small></i>`,
  `Wisdom gives strength to the wise men more than ten rulers that are in a city\n\n<i><small>ECCLESIASTES 7:19</small></i>`,
  `Surely there is not a righteous man on earth who does good and never sins\n\n<i><small>ECCLESIASTES 7:20</small></i>`,
  `For to you is born this day in the city of David a Savior, who is Christ the Lord\n\n<i><small>LUKE 2:11</small></i>`,
  `The Lord will keep you from all evil; He will keep your life\n\n<i><small>PSALM 121:7</small></i>`,
  `If the world hates you, know that it has hated Me before it hated you\n\n<i><small>JOHN 15:18</small></i>`,
  `Jesus answered him, "Because I said to you, I saw you under the fig tree, do you believe? You shall see greater things than these"\n\n<i><small>JOHN 1:50</small></i>`,
  `But the Lord said to Samuel, "Do not look on his appearance or on the height of his stature, because I have rejected him; for the Lord sees not as man sees; man looks on the outward appearance, but the Lord looks on the heart"\n\n<i><small>1 SAMUEL 16:7</small></i>`
];

function newVerse() {
  var randomNumber = Math.floor(Math.random() * verse.length);
  document.getElementById("verseDisplay").innerHTML = verse[randomNumber];
}
